fixtures:
  forge_modules:
    apt:
      repo: 'puppetlabs/apt'
      ref: '2.4.0'
    concat:
      repo: 'puppetlabs/concat'
      ref: '2.2.1'
    epel: 'stahnma/epel'
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '4.12.0'
  symlinks:
    amavisd: "#{source_dir}"
