fixtures:
  forge_modules:
    apt: 'puppetlabs/apt'
    concat: 'puppetlabs/concat'
    epel: 'stahnma/epel'
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '4.12.0'
  symlinks:
    amavisd: "#{source_dir}"
